"""event_error

Revision ID: 1eab2c3eb45e
Revises: eb5e72293a8e
Create Date: 2024-10-24 12:03:24.118937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector
from langflow.utils import migration
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '1eab2c3eb45e'
down_revision: Union[str, None] = 'eb5e72293a8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vertex_build')
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('content_blocks', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('content_blocks')
        batch_op.drop_column('category')
        batch_op.drop_column('meta_data')

    op.create_table('vertex_build',
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('data', sqlite.JSON(), nullable=True),
    sa.Column('artifacts', sqlite.JSON(), nullable=True),
    sa.Column('params', sa.TEXT(), nullable=True),
    sa.Column('build_id', sa.CHAR(length=32), nullable=False),
    sa.Column('flow_id', sa.CHAR(length=32), nullable=False),
    sa.Column('valid', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['flow_id'], ['flow.id'], name='fk_vertex_build_flow_id'),
    sa.PrimaryKeyConstraint('build_id')
    )
    # ### end Alembic commands ###
